---

apiVersion: apps/v1
kind: Deployment

metadata:
  annotations:
    deployment.kubernetes.io/revision: "postgres1.0"
    # For deployment history
    kubernetes.io/change-cause: "ver postgres1.0"
  labels:
    run: postgres
  name: postgres-deployment
  namespace: default

spec:
  # Time to wait after seeing pod becoming healthy
  # and proceeding to rolling update 
  minReadySeconds: 10

  # Timeout for deployment state
  progressDeadlineSeconds: 60

  # Available rollback history
  revisionHistoryLimit: 12

  replicas: 1
  selector:
    matchLabels:
      run: postgres

  strategy:
    rollingUpdate:
      #maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

  template:
    metadata:
      labels:
        run: postgres
    spec:
      containers:
      - image: syedalijabir/mse-postgres
        name: postgres
        imagePullPolicy: Always
        # Exposed ports
        ports:
        - containerPort: 5432
          name: postgres-port
          protocol: TCP

        # args: ["-c", "ssl=on","-c", "ssl_cert_file=/tls-cert/tls.pem","-c", "ssl_key_file=/tls-key/tls.key"]

        env:
        - name: POSTGRES_PASSWORD
          value: "linode123"
        - name: POSTGRES_DB
          value: "linode"

        volumeMounts:
        - name: tls-cert
          mountPath: "/tls-cert"
          readOnly: true
        - name: tls-key
          mountPath: "/tls-key"

      volumes:
      - name: tls-cert
        secret:
          secretName: postgres-tls-pem
      - name: tls-key
        secret:
          secretName: postgres-tls-key
          defaultMode: 384 # 0600

      dnsPolicy: ClusterFirst
      restartPolicy: Always

...

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    run: postgres

...

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-tls-pem
data:
  tls.pem: <BASE64_CRT>
type: Opaque

...

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-tls-key
data:
  tls.key: <BASE64_KEY>
type: Opaque

...
