---

apiVersion: batch/v1
kind: Job

metadata:
  name: kuard-job-once

spec:
  template:
    metadata:
      labels:
        name: kuard-pod-job
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        imagePullPolicy: Always
        args:
        - "--keygen-enable"
        - "--keygen-exit-on-complete"
        - "--keygen-num-to-gen=10"
      restartPolicy: OnFailure


...