---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
  name: kuard-hpa
  namespace: default

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: kuard-rs
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

...