---

apiVersion: apps/v1
kind: ReplicaSet

metadata:
  # Replica set unique name
  name: kuard-rs

spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kuard"
      version: "2"
  template:
    metadata:
      labels:
        app: "kuard"
        version: "2"
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:2
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          
...