---

apiVersion: apps/v1
kind: Deployment

metadata:
  annotations:
    deployment.kubernetes.io/revision: "1.2"
    # For deployment history
    kubernetes.io/change-cause: "Update nginx to 1.16"
  labels:
    run: nginx
  name: nginx-deployment
  namespace: default

spec:
  # Time to wait after seeing pod becoming healthy
  # and proceeding to rolling update 
  minReadySeconds: 60

  # Timeout for deployment state
  progressDeadlineSeconds: 600

  # Available rollback history
  revisionHistoryLimit: 12

  replicas: 4
  selector:
    matchLabels:
      run: nginx

  strategy:
    rollingUpdate:
      #maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx:1.16
        name: nginx-container
        imagePullPolicy: Always
      dnsPolicy: ClusterFirst
      restartPolicy: Always

...
