---

apiVersion: v1
kind: Pod

metadata:
  name: jenkins-pod

spec:
  containers:
  - image: jenkins/jenkins:lts-slim
    name: jenkins-container

    # Volumes
    volumeMounts:
    - mountPath: /var/jenkins_home
      name: jenkins-data

    # Resource allocation
    resources:
      # Max
      limits:
        cpu: "1000m"
        memory: "1536Mi"


    # Exposed ports
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP

  volumes:
  - name: jenkins-data
    hostPath:
      path: <path-to-persistent-storage>
...